repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: cppcheck
        name: cppcheck
        entry: cppcheck
        args:
          - --enable=warning,performance,portability
          - --std=c11
          - --suppress=missingIncludeSystem
          - --error-exitcode=1
          - -I
          - include/
          - --quiet
        language: system
        files: \.(c|h)$
        exclude: ^(vendor|tests)/

      - id: cmake-build
        name: cmake build
        entry: bash -c 'cmake --build build 2>&1 | grep -E "(error|warning)" || true'
        language: system
        pass_filenames: false
        always_run: true

      - id: ctest
        name: run tests
        entry: bash -c 'cd build && ctest --output-on-failure --quiet'
        language: system
        pass_filenames: false
        always_run: true
